**Listing 2.1 Loading the MNIST dataset in Keras**

In [2]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 1s 0us/step


In [3]:
print(len(train_images))
print(len(train_labels))

60000
60000


In [4]:
print(len(test_images))
print(len(test_labels))

10000
10000


In [5]:
print(test_images.shape)
train_images.shape

(10000, 28, 28)


(60000, 28, 28)

In [6]:
import matplotlib.pyplot as plt
digit = train_images(60000-1)
digit.shape


TypeError: ignored

In [7]:
import numpy as np
print(train_labels)
print(np.unique(train_labels))

[5 0 4 ... 5 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
print(test_labels)
print(np.unique(test_labels))

[7 2 1 ... 4 5 6]
[0 1 2 3 4 5 6 7 8 9]


**Listing 2.2 The network architecture**

In [9]:
from tensorflow.keras import models
from tensorflow.keras import layers

network = models.Sequential()

network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [ ]:
digit.reshape(28*28).shape

**Listing 2.3 The compilation step**

In [10]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [12]:
train_images.ndim

2

**Listing 2.4 Preparing the image data**

In [13]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255 #normalization 
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

**Listing 2.5 Preparing the labels**

In [14]:
train_labels[0]

5

In [16]:
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [17]:
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

**Now train your Model**

In [18]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 1s 2ms/step - loss: 1.4760 - accuracy: 0.6800
Epoch 2/5
469/469 [==============================] - 1s 2ms/step - loss: 0.5871 - accuracy: 0.8526
Epoch 3/5
469/469 [==============================] - 1s 2ms/step - loss: 0.4104 - accuracy: 0.8880
Epoch 4/5
469/469 [==============================] - 1s 2ms/step - loss: 0.3528 - accuracy: 0.9000
Epoch 5/5
469/469 [==============================] - 1s 2ms/step - loss: 0.3231 - accuracy: 0.9075


In [19]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.3028 - accuracy: 0.9125
test_acc: 0.9125000238418579
