**Listing 2.1 Loading the MNIST dataset in Keras**

In [5]:
from tensorflow.keras.datasets import fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [6]:
print(len(train_images))
print(len(train_labels))

60000
60000


In [7]:
print(len(test_images))
print(len(test_labels))

10000
10000


In [8]:
print(test_images.shape)
train_images.shape

(10000, 28, 28)


(60000, 28, 28)

In [9]:
import numpy as np
print(train_labels)
print(np.unique(train_labels))

[9 0 0 ... 3 0 5]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(test_labels)
print(np.unique(test_labels))

[9 2 1 ... 8 1 5]
[0 1 2 3 4 5 6 7 8 9]


**Listing 2.2 The network architecture**

In [11]:
from tensorflow.keras import models
from tensorflow.keras import layers

network = models.Sequential()

network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [12]:
digit.reshape(28*28).shape

NameError: ignored

Listing 2.3 The compilation step

In [13]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [14]:
train_images.ndim

3

Listing 2.4 Preparing the image data

In [15]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255 #normalization 
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

**Listing 2.5 Preparing the labels**

In [16]:
train_labels[0]

9

In [17]:
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [18]:
train_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

Now training our Model

In [19]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 4s 9ms/step - loss: 0.5646 - accuracy: 0.7997
Epoch 2/5
469/469 [==============================] - 4s 9ms/step - loss: 0.3819 - accuracy: 0.8597
Epoch 3/5
469/469 [==============================] - 4s 9ms/step - loss: 0.3361 - accuracy: 0.8766
Epoch 4/5
469/469 [==============================] - 4s 9ms/step - loss: 0.3093 - accuracy: 0.8843
Epoch 5/5
469/469 [==============================] - 4s 9ms/step - loss: 0.2911 - accuracy: 0.8931


In [20]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.3449 - accuracy: 0.8795
test_acc: 0.8794999718666077
