# Data Represention for neural network


*   nd-Array
*   List item



**2.2.1 Scalars (0D tensors)**

In [3]:
import numpy as np

x = np.array(12)
print(x)
print(x.ndim)
print(x.shape)

12
0
()


**2.2.2 Vectors (1D tensors)**

In [4]:
x = np.array([1,2,3,4,5])
print(x)
print("Dimension",x.ndim)
print("Shape",x.shape)

[1 2 3 4 5]
1
(5,)


**2.2.3 Matrices (2D tensors)**

In [5]:
x = np.array([[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]])
print(x)
print("Dimension",x.ndim)
print("Shape",x.shape)

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
Dimension 2
Shape (3, 5)


**2.2.4 3D tensors and higher-dimensional tensors**

In [6]:
x = np.array([[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]]])
print(x)
print("Dimension",x.ndim)
print("Shape",x.shape)

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]
Dimension 3
Shape (3, 3, 5)


In [7]:
x = np.arange(1,46).reshape((3,3,5))
print(x)
print("Dimension",x.ndim)
print("Shape",x.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]
Dimension 3
Shape (3, 3, 5)


In [10]:
x = np.ones((2,2,2,2,2))
print(x)
print("Dimension",x.ndim)
print("Shape",x.shape)

[[[[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]


  [[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]]



 [[[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]


  [[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]]]
Dimension 5
Shape (2, 2, 2, 2, 2)
