In [1]:
import numpy as np

In [2]:
np.sum([1,3])

4

In [3]:
np.__version__

'1.16.5'

In [4]:
!pip install --upgrade numpy

  Using cached https://files.pythonhosted.org/packages/f9/50/cd3e12bf41ac273702882610fd43bd765b8d2b99baf4295b00578fd69323/numpy-1.18.2-cp37-cp37m-win_amd64.whl
  Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\numpy\\compat\\py3k.py'
Consider using the `--user` option or check the permissions.



In [5]:
%history

import numpy as np
np.sum([1,3])
np.__version__
!pip install --upgrade numpy
%history


%run abc.py # run the file directly here
%load abc.py # It load the file  , to use it we use it refrence 

In [6]:
%time list(range(2000000))[:20]

Wall time: 321 ms


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [7]:
%time np.arange(2000000)

Wall time: 14 ms


array([      0,       1,       2, ..., 1999997, 1999998, 1999999])

In [8]:
%time np.arange(2000000)[:20]

Wall time: 12 ms


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
%time [x+5 for x in range(1,1000000)][:20]

Wall time: 656 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

In [13]:
l = list(range(1,1000000))
l2 = list(enumerate(l))
for i, v in l2:
    l[i] = l[i]+5
l[:20]
%time

Wall time: 0 ns


In [11]:
%time np.arange(1,1000000) + 5

Wall time: 17 ms


array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [14]:
l = np.arange(1,1000000)
l = l + 5
l

array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [15]:
type(l)

numpy.ndarray

In [16]:
l.shape

(999999,)

In [17]:
l.ndim

1

# Dimensions

In [19]:
a = np.array([1])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[1]
1
(1,)
int32


In [21]:
a = np.array([1,2,3,4])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[1 2 3 4]
1
(4,)
int32


In [22]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9] ])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
int32


In [25]:
# 2d adding 5 using list
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9] ])
print("Before adding 5")
print(a)
for r, rd in list(enumerate(a) ):
    #print(r,rd)
    for c , cd in list(enumerate(rd)):
        #print(c,cd)
        a[r][c] = a[r][c] + 5
print("After adding 5")
print(a)

Before adding 5
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After adding 5
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [34]:
a = np.arange(1,10).reshape((3,3))
a = a + 5
a

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [35]:
a = np.arange(1,31).reshape((3,5,2))
a = a + 5
a

array([[[ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25]],

       [[26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35]]])

In [36]:
a = np.arange(1,31).reshape((3,5,2))
a = a * 5
a

array([[[  5,  10],
        [ 15,  20],
        [ 25,  30],
        [ 35,  40],
        [ 45,  50]],

       [[ 55,  60],
        [ 65,  70],
        [ 75,  80],
        [ 85,  90],
        [ 95, 100]],

       [[105, 110],
        [115, 120],
        [125, 130],
        [135, 140],
        [145, 150]]])

In [37]:
a = np.arange(1,31).reshape((3,5,2))
a = a - 5
a

array([[[-4, -3],
        [-2, -1],
        [ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25]]])

In [39]:
a = np.arange(1,28).reshape((3,3,3))
a = a % 2
a

array([[[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]],

       [[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]]], dtype=int32)

<img src ="https://www.pythoninformer.com/img/numpy/3d-array.png" />

# Slicing 
## a[i,j,k]

In [30]:
a[2]

array([[26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35]])

In [31]:
a[2,0]

array([26, 27])

In [32]:
a[2,0,1]

27

In [41]:
a = np.random.rand(2,3,3,4,5,5)
print(a.ndim)
print(a.shape)
a = a * 10
a

6
(2, 3, 3, 4, 5, 5)


array([[[[[[2.71352988e+00, 6.38778876e+00, 4.61609009e+00,
            5.66313230e+00, 5.57857679e-01],
           [5.22179971e+00, 4.67197640e+00, 3.60466697e-01,
            4.78605445e+00, 2.81023614e+00],
           [7.30332723e+00, 8.70565051e+00, 5.63262751e+00,
            4.57227070e-01, 3.04062763e+00],
           [5.07965190e+00, 3.90033779e+00, 9.84110858e-01,
            3.00194460e+00, 6.71204559e-01],
           [1.73855330e+00, 8.00794361e-01, 5.86647523e+00,
            5.97010916e+00, 5.44857428e+00]],

          [[5.59120506e+00, 3.62911205e+00, 1.76540228e+00,
            1.95664553e+00, 5.80666511e+00],
           [6.11105183e-01, 9.45551309e+00, 3.84838418e+00,
            8.37923810e+00, 6.68546277e+00],
           [3.61451554e+00, 5.61086987e+00, 6.38191398e+00,
            9.59942250e+00, 4.39543594e+00],
           [1.19476718e+00, 7.16724231e+00, 4.14376141e+00,
            3.36818358e+00, 4.93449549e+00],
           [1.21125578e+00, 7.47806281e+00, 3.1128904

In [44]:
a = np.random.randn(2,6)
print(a)
print(a * a)


[[-0.99715796  0.95061278  0.26344739 -0.82397734  0.47627536  1.13616311]
 [ 1.16033366  0.49283058 -1.5768358   1.16264676  1.32202607 -0.32641601]]
[[0.994324   0.90366465 0.06940452 0.67893865 0.22683822 1.29086661]
 [1.3463742  0.24288198 2.48641115 1.35174748 1.74775292 0.10654741]]


In [46]:
a = np.arange(1,13).reshape(2,6)
print(a)
print(a * a)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[  1   4   9  16  25  36]
 [ 49  64  81 100 121 144]]


# Creating ndarrays

In [47]:
a  = [1,2,3]
print(type(a))
a = np.array(a)
print(a.dtype)
a.dtype
type(a)

<class 'list'>
int32


numpy.ndarray

In [48]:
a  = (1,2,3)
print(type(a))
a = np.array(a)
print(a.dtype)

<class 'tuple'>
int32


In [49]:
a  = {1,2,3}
print(type(a))
a = np.array(a)
print(a.dtype)

<class 'set'>
object


#  np.array

In [51]:
l = [1,2,3]
a = np.array(l)
b = np.array(a)
# a is l
a is b

False

In [55]:
l = [1,2,3]
a = np.asarray(l)
b = np.asarray(a)
#a is l
a is b

True