In [1]:
import numpy as np

In [2]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [3]:
a.shape = (3,9)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [4]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [7]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
np.ones_like(a) #copy the shape/dimention of defined array

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [9]:
np.empty((2,2))

array([[4.65734568e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [10]:
np.empty_like(a)

array([[4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [11]:
np.full((2,3,3),fill_value=5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [12]:
np.full_like((a),fill_value=5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Data Types for ndarrays

In [18]:
a = np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
#reshape(astype(range(1,13)))
a = np.arange(1,13).astype(np.float64).reshape((3,4))
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [17]:
a = np.arange(1,13).reshape((3,4)).astype(np.float64)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [21]:
a = np.arange(1,13, dtype='float').reshape(3,4)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [22]:
a = np.arange(1,13, dtype='character').reshape(3,4)
a

TypeError: data type "character" not understood

In [23]:
a = np.arange(1,13).reshape((3,4)).astype(np.character)
a

array([[b'1', b'2', b'3', b'4'],
       [b'5', b'6', b'7', b'8'],
       [b'9', b'10', b'11', b'12']], dtype='|S21')

In [26]:
a = np.array([1,2,4], dtype=np.float32)
a

array([1., 2., 4.], dtype=float32)

In [29]:
arr1 = np.array([1,2,4], dtype=np.int32)
arr1

array([1, 2, 4], dtype=int32)

In [30]:
print(a.dtype)
print(arr1.dtype)

float32
int32


In [31]:
print(type(a))
print(type(arr1))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [37]:
a = np.array([1,2,4], dtype=np.int32)
print(a.dtype)
a = np.array([1,2,4], dtype='int')
print(a.dtype)

a = np.array([1,2,4], dtype='f2')
print(a.dtype)

a = np.array([1,2,4], dtype='i1')
print(a.dtype)
a = np.array([1,2,4], dtype='u1')
print(a.dtype)

a = np.array([1,2,4], dtype='i4')
print(a.dtype)
a = np.array([1,2,4], dtype='u4')
print(a.dtype)
a = np.array([1,2,4], dtype='i8')
print(a.dtype)

a = np.array([1,2,4], dtype='u8')
print(a.dtype)

int32
int64
float16
int8
uint8
int32
uint32
int64
uint64


In [36]:
a = np.array([1,2,4], dtype='f4')
print(a.dtype)
a = np.array([1,2,4], dtype='f8')
print(a.dtype)

a = np.array([1,2,4], dtype='d')
print(a.dtype)

a = np.array([1,2,4], dtype='f16')
print(a.dtype)

a = np.array([1,2,4], dtype='g')
print(a.dtype)


float32
float64
float64
float128
float128


In [34]:
def abc(x):
    try:
        x = str(x)
        return np.int64("".join([i for i in x if str.isnumeric(i)]))
    except:
        return 0
abc("ghdfkhgluncfhguvreklcsdcnkhh;chahs3")

3

In [38]:
a = np.arange(1,12, dtype = np.float64)
b = np.arange(1,4)
print(a.dtype)
print(b.dtype)

float64
int64


In [39]:
b.astype(a.dtype)

array([1., 2., 3.])

In [40]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [41]:
a % 5 == 0

array([[[False, False, False],
        [False,  True, False],
        [False, False, False]],

       [[ True, False, False],
        [False, False,  True],
        [False, False, False]],

       [[False,  True, False],
        [False, False, False],
        [ True, False, False]]])

In [42]:
a[a % 5 == 0]

array([ 5, 10, 15, 20, 25])

In [43]:
a[(a % 5 == 0) & (a % 3 == 0)]

array([15])

In [44]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [45]:
a[1][1][1]

14

In [46]:
a[1,1,1]

14

In [47]:
a[1:]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [48]:
a[1:,1:,:1]

array([[[13],
        [16]],

       [[22],
        [25]]])

In [50]:
a[1:][1:][1:]

array([], shape=(0, 3, 3), dtype=int64)

In [51]:
a[1:][1:][:1]

array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])