In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,10,size=11)
b = np.random.randint(1,5,size=5)
print(a,b, sep='\n\n')

[2 5 4 2 1 6 4 2 5 8 4]

[2 3 3 4 3]


In [3]:
a = np.random.randint(1,20,size=20)
b = np.random.randint(1,10,size=10)
print(a,b, sep='\n\n')

[ 6 11 15 17 17 19  2 15  6  7 16 19  4 14 12 14  6 11  6 18]

[6 5 3 1 9 3 5 8 7 6]


In [6]:
[True if x in a else False for x in b ]

[True, False, False, False, False, False, False, False, True, True]

In [9]:
np.in1d(b,a)

array([ True, False, False, False, False, False, False, False,  True,
        True])

In [10]:
a = np.random.randint(1,1000,size=1000)
b = np.random.randint(1,500,size=500)
print(a,b, sep='\n\n')

[  9   2 135 383 131 249 784 323 719 575 940 213  67 734 791 489 224 510
 778 812  30 268 523  34  75 305 841 903 671 275 305 121 730 581 840  37
 506 265 467 424 608 104  32 515 703 993 995 611 313 264 126 431 677 520
 511 957 782 701 585 555 774 697  20 274 685 129 542 507 271 175 930 931
 791 403 498 960 365 248 325 805 374 307 895 259 306 623 592  55 896 760
 165 768 807 576 888 724 520 912 253 650 703 873 364 307  27 854 943  18
 815 120 154 358 215 274 872 650 784 897 645 262 337 406 896 521 755 497
 794 528 766 816 398 722 415 216 793  39 317 549 826 299 303 292 181 337
 496 392 244 805 308 136 657 597 381 253 351 692 990 334 995 189 816 881
 356 817 964 507 298 810 725 159 943 900 918 605 911 760 136 127 101  27
 816 627 242 129 417 908 761 388 167 433 452 372 321 398 589 820  53 609
 373 883 194 277 778  84 391 624 956  88 819 981 756  93  60 419 960 174
 621 671 320 406  43 212 446 382  34 163 201 722 880 537 236 688 355  68
 301 643 976 511 215 814 297  73  49 926 905 948 81

In [11]:
[True if x in a else False for x in b ]

[False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 Tru

In [12]:
np.in1d(b,a)

array([False,  True,  True, False, False,  True,  True, False, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True, False,  True,  True, False,  True,  True,  True, False,
       False,  True, False,  True,  True,  True, False,  True, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True, False, False,
        True,  True,  True, False,  True,  True, False,  True, False,
        True, False,

## Stacking

In [13]:
a = np.arange(1,11)
b = a * 3
print(a , b , sep='\n\n')

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


In [14]:
np.stack((a,b), axis=0) #Default axis = 0 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [15]:
np.stack((a,b), axis=1) 

array([[ 1,  3],
       [ 2,  6],
       [ 3,  9],
       [ 4, 12],
       [ 5, 15],
       [ 6, 18],
       [ 7, 21],
       [ 8, 24],
       [ 9, 27],
       [10, 30]])

In [17]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  6,  9, 12, 15, 18, 21,
       24, 27, 30])

In [18]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [19]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 10
print(a,b , sep ='\n\n')

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]


In [20]:
np.dstack((a,b)) #

array([[[ 0,  1, 10, 11],
        [ 2,  3, 12, 13]],

       [[ 4,  5, 14, 15],
        [ 6,  7, 16, 17]]])

In [21]:
a = np.arange(2*2).reshape(2,2)
print(a)
a+5

[[0 1]
 [2 3]]


array([[5, 6],
       [7, 8]])

In [25]:
b = np.full_like(a,5)
print(a,b, sep='\n\n')

[[0 1]
 [2 3]]

[[5 5]
 [5 5]]


In [26]:
a + b

array([[5, 6],
       [7, 8]])

In [27]:
a = np.arange(1,11)
b= a*3
print(a,b, sep='\n\n')
np.row_stack((a,b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [28]:
a = np.arange(1,11)
b= a*3
print(a,b, sep='\n\n')
np.column_stack((a,b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  3],
       [ 2,  6],
       [ 3,  9],
       [ 4, 12],
       [ 5, 15],
       [ 6, 18],
       [ 7, 21],
       [ 8, 24],
       [ 9, 27],
       [10, 30]])

In [29]:
a = np.arange(1,11)
b= a*3
print(a,b, sep='\n\n')
np.hstack((a,b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  6,  9, 12, 15, 18, 21,
       24, 27, 30])

In [30]:
a = np.arange(1,11)
b= a*3
print(a,b, sep='\n\n')
np.vstack((a,b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [31]:
a = np.random.randn(6,5)
a

array([[ 1.03522784, -0.3312804 , -0.5689744 ,  1.18312902, -1.11004233],
       [ 0.68975543, -0.88402854,  0.9233411 , -2.5983025 ,  1.12439224],
       [ 0.25680397, -1.25811704,  0.69309162, -0.51198131, -2.46793915],
       [-0.06034137,  1.40084099,  1.05453133, -1.16008382,  1.43539672],
       [-0.80528367,  0.22789263, -1.11866732,  0.06391361,  0.21895168],
       [-0.18348185,  1.36014162,  1.17329907, -0.29768947,  0.21700931]])

In [32]:
a = np.arange(6*5).reshape((6,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [33]:
print(a)
np.split(a,3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [34]:
print(a)
np.split(a,6)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29]])]

In [35]:
print(a)
np.split(a,2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [36]:
print(a)
np.split(a,5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


ValueError: array split does not result in an equal division

In [38]:
a = np.arange(6*6).reshape((6,6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [39]:
print(a)
np.split(a,3, axis =1 )

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [40]:
print(a)
np.hsplit(a,3 )

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [41]:
print(a)
np.vsplit(a,3 )

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [43]:
a = np.random.randint(1,20,size=20)
b = np.random.randint(1,10,size=10)
print(a,b, sep='\n\n')
np.intersect1d(a,b)

[19  7 17 17 19 16  1  9 14  4 10  6  8  9  8 19  2  9  4  5]

[1 2 2 3 1 7 7 8 7 3]


array([1, 2, 7, 8])

In [44]:
a = np.random.randint(1,20,size=20)
b = np.random.randint(1,10,size=10)
print(a,b, sep='\n\n')
np.union1d(a,b)

[11 13  8 14 13 18  1 15 18  5  4 12  5 19  8  3 13 15 14  5]

[6 2 4 8 6 1 6 2 5 6]


array([ 1,  2,  3,  4,  5,  6,  8, 11, 12, 13, 14, 15, 18, 19])

In [45]:
a = np.random.randint(1,20,size=20)
b = np.random.randint(1,10,size=10)
print(a,b, sep='\n\n')
np.setdiff1d(a,b)

[ 2  2 19  9  7  6 17  1 15 17  5 19 18 13 16 14 11 13  4  2]

[2 4 7 7 4 1 8 6 2 6]


array([ 5,  9, 11, 13, 14, 15, 16, 17, 18, 19])

In [47]:
a = np.random.randint(1,20,size=20)
b = np.random.randint(1,10,size=10)
print(a,b, sep='\n\n')
np.setxor1d(a,b)

[ 4 18 18 13 12 15 12  4 17 12 10 15 12 12 17 19 18 16 10  4]

[1 5 2 7 6 7 8 1 7 8]


array([ 1,  2,  4,  5,  6,  7,  8, 10, 12, 13, 15, 16, 17, 18, 19])