In [1]:
import numpy as np

In [2]:
x = [[1,3,5],[7,9,0]]

In [7]:
arr1 = np.array(x)
arr1

array([[1, 3, 5],
       [7, 9, 0]])

In [4]:
y = [[11,13,15],[17,9,11]]

In [8]:
arr2 = np.array(y)
arr2

array([[11, 13, 15],
       [17,  9, 11]])

In [6]:
np.concatenate((arr1,arr2),axis = 0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17,  9, 11]])

In [9]:
np.concatenate((arr1,arr2),axis = 1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17,  9, 11]])

In [11]:
np.vstack((arr1,arr2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17,  9, 11]])

In [12]:
np.hstack((arr1,arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17,  9, 11]])