In [1]:
import numpy as np

In [2]:
d = np.array([1,5,7,8])
d

array([1, 5, 7, 8])

In [7]:
np.repeat(d,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [4]:
np.tile(d,2)

array([1, 5, 7, 8, 1, 5, 7, 8])

In [5]:
np.tile(d,3)

array([1, 5, 7, 8, 1, 5, 7, 8, 1, 5, 7, 8])

In [9]:
dt = np.array([[1,5,7,8],[1,5,7,8]])
dt

array([[1, 5, 7, 8],
       [1, 5, 7, 8]])

In [13]:
np.repeat(dt,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8, 1, 1, 1, 5, 5, 5, 7, 7, 7, 8,
       8, 8])

In [14]:
np.repeat(dt,2)

array([1, 1, 5, 5, 7, 7, 8, 8, 1, 1, 5, 5, 7, 7, 8, 8])

In [15]:
np.repeat(dt,1)

array([1, 5, 7, 8, 1, 5, 7, 8])

In [16]:
np.tile(dt,2)

array([[1, 5, 7, 8, 1, 5, 7, 8],
       [1, 5, 7, 8, 1, 5, 7, 8]])

In [17]:
np.tile(dt,3)

array([[1, 5, 7, 8, 1, 5, 7, 8, 1, 5, 7, 8],
       [1, 5, 7, 8, 1, 5, 7, 8, 1, 5, 7, 8]])